//Read a single digit number and write the number in word
let value =Math.floor(Math.random()*10);
console.log("for value  : "+value+" Day is :");
if(value==0)
console.log("zero")
else if(value==1)
console.log("one")
else if(value==2)
console.log("two")
else if(value==3)
console.log("three")
else if(value==4)
console.log("four")
else if(value==5)
console.log("five")
else if(value==6)
console.log("six")
else if(value==7)
console.log("seven")
else if(value==8)
console.log("eight")
else if(value==9)
console.log("nine")
else
console.log("Yamini")